BlogPosts:
    type: entity
    table: blog_posts
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        content:
            type: string
            nullable: false
            length: 512
            options:
                fixed: false
        created:
            type: date
            nullable: false
        categoryId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: category_id
    lifecycleCallbacks: {  }
