#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_test:
    path: /test
    controller: App\Controller\Add\DefaultController::index

#app_lucky_number:
#    path: /lucky/number
#    controller: App\Controller\Add\DefaultController::number

# action sample
app_tests:
    path: /inex_action
    controller: App\Controller\Add\DefaultController:indexAction

#add:
#    path: /add
#    controller: App\Controller\Add\AddController:add

# Routes Duplication, with /categories/search (post)
search:
    path: /search
    controller: App\Controller\Blog\CategoryController:search

category_delete:
    path: /category_delete
    controller: App\Controller\Blog\CategoryController:destroy

post_delete:
    path: /post_delete
    controller: App\Controller\Blog\BlogPostController:destroy

