#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_test:
    path: /test
    controller: App\Controller\Add\DefaultController::index

#app_lucky_number:
#    path: /lucky/number
#    controller: App\Controller\Add\DefaultController::number

app_tests:
    path: /inex_action
    controller: App\Controller\Add\DefaultController:indexAction

#add:
#    path: /add
#    controller: App\Controller\Admin\HomeController:add

search:
    path: /search
    controller: App\Controller\Blog\BlogController:search

category_delete:
    path: /category_delete
    controller: App\Controller\Blog\CategoryController:destroy

